
use_frameworks!
def library
  pod 'Alamofire'
  pod 'GBDeviceInfo'
end
target 'webtask-demo' do
  pod 'MBProgressHUD'
  library
end
target 'webtask-demoTests' do
  library
  pod 'Quick', '~> 0.9.1'
  pod 'Nimble', '3.2.0'
  pod 'OHHTTPStubs', '~> 5.1.0'
  pod 'OHHTTPStubs/Swift', '~> 5.1.0'
  pod 'OHHTTPStubs/NSURLSession', '~> 5.1.0'
end
